### ISSUE TITLE
Keine Daten abrufbar!

### ISSUE THREAD

**Issue by LenMPorath** [whosFritz/MensiMates#155]
![image](https://github.com/whosFritz/MensiMates/assets/125283275/2c59913a-1768-419c-bb55-8336aee36a66)

Keine Daten abrufbar!1

**Comment by whosFritz** [comment]
Dear Len Marten Porath,

We hope this message finds you well. We want to inform you about a temporary disruption in the data connection for the MensiMates app. Our team is actively working on resolving the issue and restoring the data connection as quickly as possible.

Currently, we are collaborating closely with the interface engineers to address the underlying causes of the disruption. Rest assured that our top priority is to minimize any inconvenience this may cause and to ensure a seamless experience for all MensiMates users.

We understand the importance of a reliable data connection for the proper functioning of the app, especially in providing timely and accurate information. Please bear with us as we work diligently to resolve this issue.

We appreciate your patience and understanding during this time. If you have any further concerns or questions, please feel free to reach out to our support team at support@mensimates.com.

Thank you for being a valued part of the MensiMates community.

Best regards,

MensiMates Support Team

**Comment by LenMPorath** [comment]
![image](https://github.com/whosFritz/MensiMates/assets/125283275/939ccf3b-d2f1-4b96-94c9-2587ca9dea42)
